### ISSUE TITLE
how to run micro-benchmarks?

### ISSUE THREAD

**Issue by LiYuTingxxn** [CGCL-codes/PRDMA#5]
hello! I am interested in pRDMA which is an admirable work! Recently I tried to run the source code, but have some troubles and hope to get your help. Can you elaborate on the meaning of the various parameters in the config.xml file? I followed the tutorial in the readme to compile successfully, on the server side./server, on the client side./client 64 500000. But neither machine has any output. Looking forward to your reply!

**Comment by Lhoddy** [comment]
Maybe the rdma link was not established successfully, you can try to open the **#define DEBUG_ON** flag in _src/dhmp_log.c_ to see if there is any output related to the link establishment.

**Comment by LiYuTingxxn** [comment]
Thanks for your reply! After open the #define DEBUG_ON flag, the output message appears.
